// Get post action types
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';

// Update post form action types
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_BODY = 'CHANGE_BODY';
export const CHANGE_AUTHOR = 'CHANGE_AUTHOR';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const SET_POST = 'SET_POST';

// Category actions
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';

// Post action types
export const SUBMIT_POST_PENDING = 'SUBMIT_POST_PENDING';
export const SUBMIT_POST_FULFILLED = 'SUBMIT_POST_FULFILLED';
export const SUBMIT_POST_REJECTED = 'SUBMIT_POST_REJECTED';
