// Get post action types
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
export const ORDER_POSTS_BY_DATE = 'ORDER_POSTS_BY_DATE';
export const ORDER_POSTS_BY_VOTES = 'ORDER_POSTS_BY_VOTES';
export const POST_UPVOTE = 'POST_UPVOTE';
export const POST_DOWNVOTE = 'POST_DOWNVOTE';
export const DELETE_POST = 'DELETE_POST';

// Update post form action types
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_BODY = 'CHANGE_BODY';
export const CHANGE_AUTHOR = 'CHANGE_AUTHOR';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const SET_POST = 'SET_POST';

// Category actions
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';

// Add category actions
export const CHANGE_ADD_CATEGORY = 'CHANGE_ADD_CATEGORY';
export const ADD_CATEGORY_PENDING = 'ADD_CATEGORY_PENDING';
export const ADD_CATEGORY_FULFILLED = 'ADD_CATEGORY_FULFILLED';
export const ADD_CATEGORY_REJECTED = 'ADD_CATEGORY_REJECTED';

// Post action types
export const SUBMIT_POST_PENDING = 'SUBMIT_POST_PENDING';
export const SUBMIT_POST_FULFILLED = 'SUBMIT_POST_FULFILLED';
export const SUBMIT_POST_REJECTED = 'SUBMIT_POST_REJECTED';
export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';

// Alert action types
export const PUSH_ALERT = 'PUSH_ALERT';
export const POP_ALERT = 'POP_ALERT';

// Comment action types
export const COMMENT_CHANGE_AUTHOR = 'COMMENT_CHANGE_AUTHOR';
export const COMMENT_CHANGE_COMMENT = 'COMMENT_CHANGE_COMMENT';
export const COMMENT_RESET_ALL = 'COMMENT_RESET_ALL';
export const SUBMIT_COMMENT_PENDING = 'SUBMIT_COMMENT_PENDING';
export const SUBMIT_COMMENT_FULFILLED = 'SUBMIT_COMMENT_FULFILLED';
export const SUBMIT_COMMENT_REJECTED = 'SUBMIT_COMMENT_REJECTED';
export const UPVOTE_COMMENT_FULLFILLED = 'UPVOTE_COMMENT_FULLFILLED';
export const DOWNVOTE_COMMENT_FULLFILLED = 'DOWNVOTE_COMMENT_FULLFILLED';
export const DELETE_COMMENT_FULFILLED = 'DELETE_COMMENT_FULFILLED';

// Edit post action types
export const EDIT_CHANGE_AUTHOR = 'EDIT_CHANGE_AUTHOR';
export const EDIT_CHANGE_TITLE = 'EDIT_CHANGE_TITLE';
export const EDIT_CHANGE_BODY = 'EDIT_CHANGE_BODY';
export const EDIT_CHANGE_CATEGORY = 'EDIT_CHANGE_CATEGORY';
export const EDIT_SUBMIT_FULLFILLED = 'EDIT_SUBMIT_FULLFILLED';
export const EDIT_SET_POST ='EDIT_SET_POST';
export const EDIT_GET_POST_FULLFILLED = 'EDIT_GET_POST_FULLFILLED';

// Edit comment action types
export const EDIT_COMMENT_SET_COMMENT = 'EDIT_COMMENT_SET_COMMENT';
export const EDIT_COMMENT_CHANGE_COMMENT = 'EDIT_COMMENT_CHANGE_COMMENT';
export const EDIT_COMMENT_CHANGE_AUTHOR = 'EDIT_COMMENT_CHANGE_AUTHOR';
export const EDIT_COMMENT_SUBMIT_FULFILLED = 'EDIT_COMMENT_SUBMIT_FULFILLED';
export const EDIT_COMMENT_SUBMIT_PENDING = 'EDIT_COMMENT_SUBMIT_PENDING';
export const EDIT_COMMENT_SUBMIT_REJECTED = 'EDIT_COMMENT_SUBMIT_REJECTED';
export const EDIT_COMMENT_CANCELED = 'EDIT_COMMENT_CANCELED';
