// Get post action types
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
export const ORDER_POSTS_BY_DATE = 'ORDER_POSTS_BY_DATE';
export const ORDER_POSTS_BY_VOTES = 'ORDER_POSTS_BY_VOTES';
export const POST_UPVOTE = 'POST_UPVOTE';
export const POST_DOWNVOTE = 'POST_DOWNVOTE';
export const DELETE_POST = 'DELETE_POST';

// Update post form action types
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_BODY = 'CHANGE_BODY';
export const CHANGE_AUTHOR = 'CHANGE_AUTHOR';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const SET_POST = 'SET_POST';

// Category actions
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';

// Post action types
export const SUBMIT_POST_PENDING = 'SUBMIT_POST_PENDING';
export const SUBMIT_POST_FULFILLED = 'SUBMIT_POST_FULFILLED';
export const SUBMIT_POST_REJECTED = 'SUBMIT_POST_REJECTED';
export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';

// Alert action types
export const PUSH_ALERT = 'PUSH_ALERT';
export const POP_ALERT = 'POP_ALERT';

// Comment action types
export const COMMENT_CHANGE_AUTHOR = 'COMMENT_CHANGE_AUTHOR';
export const COMMENT_CHANGE_COMMENT = 'COMMENT_CHANGE_COMMENT';
export const COMMENT_RESET_ALL = 'COMMENT_RESET_ALL';
export const SUBMIT_COMMENT_PENDING = 'SUBMIT_COMMENT_PENDING';
export const SUBMIT_COMMENT_FULFILLED = 'SUBMIT_COMMENT_FULFILLED';
export const SUBMIT_COMMENT_REJECTED = 'SUBMIT_COMMENT_REJECTED';
